dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
live_contract:
        address: '0xDB1Cb1d3B62469497eB61C6cbc83D301BC84e9E3'
networks:
  default: development
  development:
    verify: False
  rinkeby:
    simple_collectible: '0x41f70a6b5FA43a31116C19eb4EaFF09d1B3fa983'
    verify: False
  mainnet-fork:
    verify: False
